export const ROUTES = {
    LOGIN: '/login',
    DASHBOARD: '/admin/dashboard',
    TOURS_LIST: '/admin/tours',
    TOURS_CREATE: '/admin/tours/create',
    TOURS_EDIT: '/admin/tours/:id/edit',
    TOURS_DETAIL: '/admin/tours/:id',
    TOURS_CATEGORIES: '/admin/tour-categories',
    TOURS_SCHEDULES: '/admin/tour-schedules',
    TOURS_SCHEDULE_CREATE: '/admin/tours/:id/schedules/create',
    TOURS_SCHEDULE_EDIT: '/admin/tour-schedules/:id/edit',
    LOCATIONS_LIST: '/admin/locations',
    LOCATIONS_CREATE: '/admin/locations/create',
    LOCATIONS_EDIT: '/admin/locations/:id/edit',
    LOCATIONS_DETAIL: '/admin/locations/:id',
    LOCATIONS_CATEGORIES: '/admin/categories',
} as const;
