export const ROUTES = {
    LOGIN: '/login',
    DASHBOARD: '/dashboard',
    TOURS_LIST: '/admin/tours/list',
    TOURS_CREATE: '/admin/tours/create',
    TOURS_EDIT: '/admin/tours/edit/:id',
    TOURS_CATEGORIES: '/admin/tours/categories',
    TOURS_SCHEDULES: '/admin/tours/schedules',
    TOURS_SCHEDULE_CREATE: '/admin/tours/:id/schedules/create',
    TOURS_SCHEDULE_EDIT: '/admin/tours/schedules/edit/:id',
    LOCATIONS_LIST: '/admin/locations',
    LOCATIONS_CREATE: '/admin/locations/create',
    LOCATIONS_EDIT: '/admin/locations/edit/:id',
    LOCATIONS_DETAIL: '/admin/locations/detail/:id',
    LOCATIONS_CATEGORIES: '/admin/locations/categories',
    BOOKINGS_LIST: '/admin/bookings',
    BOOKINGS_DETAIL: '/admin/bookings/detail/:id',
    PAYMENTS_LIST: '/admin/payments',
    PAYMENTS_DETAIL: '/admin/payments/detail/:id',
    REPORTS_RATINGS: '/admin/reports/ratings',
    REPORTS_BOOKINGS: '/admin/reports/bookings',
    REPORTS_REVENUE: '/admin/reports/revenue',
    REPORTS_LOCATIONS: '/admin/reports/locations',
    REPORTS_USERS: '/admin/reports/users',
    USERS_LIST: '/admin/users',
    USERS_CREATE: '/admin/users/create',
    USERS_DETAIL: '/admin/users/detail/:id',
    USERS_EDIT: '/admin/users/edit/:id',
    NOTIFICATIONS: '/admin/notifications',
    NOTIFICATIONS_SEND: '/admin/notifications/send',
    CONTACTS: '/admin/contacts',
    BLOG_POSTS: '/admin/blog-posts',
    BLOG_POSTS_CREATE: '/admin/blog-posts/create',
    BLOG_POSTS_EDIT: '/admin/blog-posts/edit/:id',
} as const;

