import {
    Activity,
    Award,
    BaggageClaim,
    Bed,
    Bike,
    Briefcase,
    Building2,
    Bus,
    Camera,
    Car,
    Cloud,
    Coffee,
    Compass,
    Flag,
    FolderOpen,
    Globe,
    Heart,
    HelpCircle,
    Hotel,
    House,
    Landmark,
    Map,
    MapPin,
    MapPinned,
    Moon,
    Mountain,
    Music,
    Navigation,
    Palmtree,
    Plane,
    Ship,
    ShoppingBag,
    Star,
    Sun,
    Tent,
    Ticket,
    TrainFront,
    Trees,
    Umbrella,
    Utensils,
    UtensilsCrossed,
    Waves,
    Wind,
    Wine,
    type LucideIcon,
} from 'lucide-react';

const CATEGORY_ICON_COMPONENTS: Record<string, LucideIcon> = {
    Activity,
    Award,
    Bed,
    Bike,
    Briefcase,
    Building2,
    Bus,
    Camera,
    Car,
    Cloud,
    Coffee,
    Compass,
    Flag,
    FolderOpen,
    Globe,
    Heart,
    HelpCircle,
    Hotel,
    House,
    Landmark,
    Map,
    MapPin,
    MapPinned,
    Moon,
    Mountain,
    Music,
    Navigation,
    Palmtree,
    Plane,
    Ship,
    ShoppingBag,
    Star,
    Suitcase: BaggageClaim,
    Sun,
    Tent,
    Ticket,
    Tram: TrainFront,
    Trees,
    Umbrella,
    Utensils,
    UtensilsCrossed,
    Waves,
    Wind,
    Wine,
};

const LEGACY_ICON_ALIASES: Record<string, string> = {
    'international-dining': 'UtensilsCrossed',
    'local-dining': 'UtensilsCrossed',
    'restaurant': 'UtensilsCrossed',
    'restaurant-menu': 'UtensilsCrossed',
    'seafood': 'UtensilsCrossed',
    'local-cafe': 'Coffee',
    'cafe': 'Coffee',
    'coffee-shop': 'Coffee',
    'cafe-tea': 'Coffee',
    'tea': 'Coffee',
    'pot': 'Coffee',
    'local-bar': 'Wine',
    'bar': 'Wine',
    'nightlife': 'Wine',
    'glass': 'Wine',
    'hotel': 'Hotel',
    'hotel-class': 'Hotel',
    'luxury-stay': 'Hotel',
    'accommodation': 'Hotel',
    'stars': 'Hotel',
    'villa': 'House',
    'home': 'House',
    'real-estate': 'House',
    'funeral': 'House',
    'museum': 'Landmark',
    'account_balance': 'Landmark',
    'temple-buddhist': 'Landmark',
    'temple': 'Landmark',
    'art': 'Landmark',
    'archive': 'Landmark',
    'education': 'Landmark',
    'library': 'Landmark',
    'hard-hat': 'Landmark',
    'park': 'Trees',
    'forest': 'Trees',
    'nature': 'Trees',
    'leaf': 'Trees',
    'carrot': 'Trees',
    'beach-access': 'Waves',
    'waves': 'Waves',
    'swim': 'Waves',
    'mountain': 'Mountain',
    'terrain': 'Mountain',
    'map': 'Map',
    'map-pinned': 'MapPinned',
    'place': 'MapPinned',
    'location-on': 'MapPinned',
    'camera-alt': 'Camera',
    'photo-camera': 'Camera',
    'attractions': 'Camera',
    'studio': 'Camera',
    'directions-bus': 'Bus',
    'bus': 'Bus',
    'transport': 'Bus',
    'delivery': 'Bus',
    'post': 'Bus',
    'directions-boat': 'Ship',
    'sailing': 'Ship',
    'ship': 'Ship',
    'shopping-bag': 'ShoppingBag',
    'shopping-cart': 'ShoppingBag',
    'shopping-mall': 'ShoppingBag',
    'local-market': 'ShoppingBag',
    'gift': 'ShoppingBag',
    'fashion': 'ShoppingBag',
    'flower': 'ShoppingBag',
    'beauty': 'ShoppingBag',
    'furniture': 'ShoppingBag',
    'electronics': 'ShoppingBag',
    'music-note': 'Music',
    'festival': 'Music',
    'cinema': 'Music',
    'music': 'Music',
    'convention': 'Music',
    'event': 'Music',
    'tent': 'Tent',
    'boot': 'Compass',
    'wind': 'Wind',
    'air': 'Plane',
    'rocket': 'Plane',
    'ticket': 'Ticket',
    'info': 'Compass',
    'water-park': 'Umbrella',
    'moon': 'Moon',
    'sport': 'Activity',
    'fitness': 'Activity',
    'bolt': 'Activity',
    'flame': 'Activity',
    'clock': 'Activity',
    'ambulance': 'Activity',
    'user': 'Activity',
    'wellness': 'Heart',
    'spa': 'Heart',
    'pet': 'Heart',
    'baby': 'Heart',
    'heart': 'Heart',
    'hospital': 'Activity',
    'dentist': 'Activity',
    'pill': 'Activity',
    'test-tube': 'Activity',
    'shield': 'Award',
    'security': 'Award',
    'dollar': 'Award',
    'wheelchair': 'Activity',
    'government': 'Building2',
    'legal': 'Building2',
    'finance': 'Building2',
    'bank': 'Building2',
    'building': 'Building2',
    'factory': 'Building2',
    'file-text': 'FolderOpen',
    'book': 'FolderOpen',
    'car-rental': 'Car',
    'travel-agency': 'Compass',
    'walk': 'Compass',
    'compass': 'Compass',
    'construction': 'Briefcase',
    'tool': 'Briefcase',
    'craft': 'Briefcase',
    'gas': 'Briefcase',
    'laundry': 'Briefcase',
    'work': 'Briefcase',
    'code': 'Briefcase',
    'briefcase': 'Briefcase',
    'translation': 'Briefcase',
    'printing': 'Briefcase',
    'pen': 'Flag',
    'box': 'Suitcase',
    'users': 'Navigation',
    'globe': 'Globe',
    'cloud': 'Cloud',
};

const toTokenKey = (value: string) =>
    value
        .trim()
        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
        .replace(/[_\s]+/g, '-')
        .replace(/[^a-zA-Z0-9-]/g, '-')
        .replace(/-+/g, '-')
        .replace(/^-|-$/g, '')
        .toLowerCase();

const toPascalCase = (value: string) =>
    toTokenKey(value)
        .split('-')
        .filter(Boolean)
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');

export const resolveCategoryIconName = (rawValue: string | null | undefined, fallback = 'Map') => {
    const value = String(rawValue || '').trim();

    if (!value) {
        return fallback;
    }

    const aliasMatch = LEGACY_ICON_ALIASES[toTokenKey(value)];
    if (aliasMatch) {
        return aliasMatch;
    }

    const pascalCaseName = toPascalCase(value);
    return pascalCaseName || fallback;
};

export const getCategoryIconComponent = (rawValue: string | null | undefined, fallback = 'Map') => {
    const iconName = resolveCategoryIconName(rawValue, fallback);
    return CATEGORY_ICON_COMPONENTS[iconName] || CATEGORY_ICON_COMPONENTS[fallback] || Map;
};
